site_name: Opsec C
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra_css:
  - stylesheets/styles.css
extra_javascript:
  - scripts/theme_changer.js
validation:
  omitted_files: ignore
  absolute_links: ignore
  unrecognized_links: ignore
  not_found: ignore
theme:
  name: material
  font:
    text: Courier New
  palette:
    scheme: custom
    primary: custom
    accent: custom
nav:
    - Home: index.md
    - General Rules: rules/tips.md
    - Game Modes:
      - Hacker: rules/gamemodes/hacker.md
      - Hacker Leaders:
        - Operation Leader: rules/gamemodes/hacker/OperationLeader.md
        # - Former Agent Leader: rules/gamemodes/hacker/FormerAgentLeader.md
        # - Hack God: rules/gamemodes/hacker/HackGod.md
        # - Infamous Cybercriminal: rules/gamemodes/hacker/InfamousCybercriminal.md
        # - Majority Shareholder: rules/gamemodes/hacker/MajorityShareholder.md
      - Interlooper: rules/gamemodes/interlooper.md
      - Interlooper Win Conditions:
        # - Journalist: rules/gamemodes/interlooper/Journalist.md
        - Investigator: rules/gamemodes/interlooper/Investigator.md
        # - Assassin: rules/gamemodes/interlooper/Assassin.md
        # - Serial Killer: rules/gamemodes/interlooper/SerialKiller.md
      - Fed: rules/gamemodes/fed.md
      - Fed Leaders:
        - Blackmailed Leader: rules/gamemodes/fed/BlackmailedLeader.md
        # - Founder of Agent: rules/gamemodes/fed/FounderOfAgent.md
      # - W3C: rules/gamemodes/w3c.md
      # - W3C Leaders:
      #   - W3C Leader: rules/gamemodes/fed/W3CLeader.md
      # - Paragon: rules/gamemodes/paragon.md
      # - Paragon Leaders:
      #   - Paragon Leader: rules/gamemodes/fed/ParagonLeader.md
    - Role Lists:
      - Simplified Role List: rules/rolelists/simplifiedrolelist.md
      - Core Role List: rules/rolelists/corerolelist.md
      - Full Role List: rules/rolelists/full3factrolelist.md
      # - Full 3 Faction Role List: rules/rolelists/full3factrolelist.md
      # - Full Role List: rules/rolelists/fullrolelist.md
    - Roles:
      - Hacker:
        - Hacker: rolelist/hacker/hacker.md
        - Hacker Special:
          - Old Friend: rolelist/hacker/HackerSpecial/OldFriend.md
          - Tech Lead: rolelist/hacker/HackerSpecial/TechLead.md
        - Hacker Field Operations:
          - Enforcer: rolelist/hacker/HackerFieldOps/Enforcer.md
          - CCTV Specialist: rolelist/hacker/HackerFieldOps/CCTVSpecialist.md
          - Rookie Hacker: rolelist/hacker/HackerFieldOps/RookieHacker.md
          - Improvised Hacker: rolelist/hacker/HackerFieldOps/ImprovisedHacker.md
          - Inside Man (Security Guard): rolelist/hacker/HackerFieldOps/InsideManSecurityGuard.md
          - Nightclub Guard: rolelist/hacker/HackerFieldOps/NightclubGuard.md
          - Hardware Hacker: rolelist/hacker/HackerFieldOps/HardwareHacker.md
          - Entertainer: rolelist/hacker/HackerFieldOps/Entertainer.md
          - Getaway Driver: rolelist/hacker/HackerFieldOps/GetawayDriver.md
          - Arms Dealer: rolelist/hacker/HackerFieldOps/ArmsDealer.md
          - Dungeon Master: rolelist/hacker/HackerFieldOps/DungeonMaster.md
        - Hacker Investigative:
          - Analyst: rolelist/hacker/HackerInvest/Analyst.md
          - Social Engineer: rolelist/hacker/HackerInvest/SocialEngineer.md
          - Computer Technician: rolelist/hacker/HackerInvest/ComputerTechnician.md
          - Inside Man (Detective): rolelist/hacker/HackerInvest/InsideManDetective.md
          - Dark Web Contact: rolelist/hacker/HackerInvest/DarkWebContact.md
          - Natural Linguist: rolelist/hacker/HackerInvest/NaturalLinguist.md
          - Computer Vision Engineer: rolelist/hacker/HackerInvest/ComputerVisionEngineer.md
          - Technical Project Manager: rolelist/hacker/HackerInvest/TechnicalProjectManager.md
          - Search Engine Optimizer: rolelist/hacker/HackerInvest/SearchEngineOptimizer.md
          - AI Generalist: rolelist/hacker/HackerInvest/AIGeneralist.md
        - Hacker Offensive:
          - Network Specialist: rolelist/hacker/HackerOffensive/NetworkSpecialist.md
          - Blackhat: rolelist/hacker/HackerOffensive/Blackhat.md
          - Prodigy: rolelist/hacker/HackerOffensive/Prodigy.md
          - Network Architect: rolelist/hacker/HackerOffensive/NetworkArchitect.md
          - Inside Man (Software Engineer): rolelist/hacker/HackerOffensive/InsideManSoftwareEngineer.md
          - Laptop Specialist: rolelist/hacker/HackerOffensive/LaptopSpecialist.md
          - Server Specialist: rolelist/hacker/HackerOffensive/ServerSpecialist.md
          - Steadfast Student: rolelist/hacker/HackerOffensive/SteadfastStudent.md
          - Graph Theorist: rolelist/hacker/HackerOffensive/GraphTheorist.md
          - Reverse Cryptographer: rolelist/hacker/HackerOffensive/ReverseCryptographer.md
        - Hacker Utility:
          - Inside Man (Assistant): rolelist/hacker/HackerUtility/InsideManAssistant.md
          - Spearphisher: rolelist/hacker/HackerUtility/Spearphisher.md
          - Hacking Instructor: rolelist/hacker/HackerUtility/HackingInstructor.md
          - Loan Shark: rolelist/hacker/HackerUtility/LoanShark.md
          - Propagandist: rolelist/hacker/HackerUtility/Propagandist.md
          - Maintenance Man: rolelist/hacker/HackerUtility/MaintenanceMan.md
          - Malware Programmer: rolelist/hacker/HackerUtility/MalwareProgrammer.md
          - Sympathetic Reporter: rolelist/hacker/HackerUtility/SympatheticReporter.md
          - Drug Dealer: rolelist/hacker/HackerUtility/DrugDealer.md
          - Criminal Coroner: rolelist/hacker/HackerUtility/CriminalCoroner.md
        - Hacker Chaos:
          - Disgraced Loyalist: rolelist/hacker/HackerChaos/DisgracedLoyalist.md
          - Double Agent: rolelist/hacker/HackerChaos/DoubleAgent.md
          - Hacking Advocate: rolelist/hacker/HackerChaos/HackingAdvocate.md
          - Technical Recruiter: rolelist/hacker/HackerChaos/TechnicalRecruiter.md
          - Silenced Investigator: rolelist/hacker/HackerChaos/SilencedInvestigator.md
          - Radio Operator: rolelist/hacker/HackerChaos/RadioOperator.md
          - Rookie Assassin: rolelist/hacker/HackerChaos/RookieAssassin.md
          - Social Media Manager: rolelist/hacker/HackerChaos/SocialMediaManager.md
          - NFT Scammer: rolelist/hacker/HackerChaos/NFTScammer.md
          - Vibe Coder: rolelist/hacker/HackerChaos/VibeCoder.md
      - Interlooper:
        - Interlooper: rolelist/interlooper/interlooper.md
        - Interlooper Special:
          - Gambling Leader: rolelist/interlooper/InterlooperSpecial/GamblingLeader.md
          - Cheeseburger Technician: rolelist/interlooper/InterlooperSpecial/CheeseburgerTechnician.md
          - The Employer: rolelist/interlooper/InterlooperSpecial/TheEmployer.md
          - Sociopath: rolelist/interlooper/InterlooperSpecial/Sociopath.md
          - Resentful Criminal: rolelist/interlooper/InterlooperSpecial/ResentfulCriminal.md
        - Interlooper Field Operations:
          - Loose Cannon: rolelist/interlooper/InterlooperFieldOps/LooseCannon.md
          - Bounty Hunter: rolelist/interlooper/InterlooperFieldOps/BountyHunter.md
          - Criminal Freelancer: rolelist/interlooper/InterlooperFieldOps/CriminalFreelancer.md
          - Insane Officer: rolelist/interlooper/InterlooperFieldOps/InsaneOfficer.md
          - Former Bodyguard: rolelist/interlooper/InterlooperFieldOps/FormerBodyguard.md
          - Contracted Headhunter: rolelist/interlooper/InterlooperFieldOps/ContractedHeadhunter.md
        - Interlooper Investigative:
          - Journalist: rolelist/interlooper/InterlooperInvest/Journalist.md
          - Double Crosser: rolelist/interlooper/InterlooperInvest/DoubleCrosser.md
          - Shamed Journalist: rolelist/interlooper/InterlooperInvest/ShamedJournalist.md
          - Amateur Investigator: rolelist/interlooper/InterlooperInvest/AmateurInvestigator.md
          - Private Investigator: rolelist/interlooper/InterlooperInvest/PrivateInvestigator.md
          - Vengeful Assassin: rolelist/interlooper/InterlooperInvest/VengefulAssassin.md
        - Interlooper Offensive:
          - Script Kiddie: rolelist/interlooper/InterlooperOffensive/ScriptKiddie.md
          - Panicked Blabbermouth: rolelist/interlooper/InterlooperOffensive/PanickedBlabbermouth.md
          - Rival Hacker: rolelist/interlooper/InterlooperOffensive/RivalHacker.md
          - Hacknet Hacker: rolelist/interlooper/InterlooperOffensive/HacknetHacker.md
          - Connection Specialist: rolelist/interlooper/InterlooperOffensive/ConnectionSpecialist.md
          - Discord Manager: rolelist/interlooper/InterlooperOffensive/DiscordManager.md
          - Network Shutdowner: rolelist/interlooper/InterlooperOffensive/NetworkShutdowner.md
        - Interlooper Utility:
          - W.P.P. Member: rolelist/interlooper/InterlooperUtility/WPPMember.md
          - Political Campaigner: rolelist/interlooper/InterlooperUtility/PoliticalCampaigner.md
          - Abandoned Agent: rolelist/interlooper/InterlooperUtility/AbandonedAgent.md
          - Retired Hacker: rolelist/interlooper/InterlooperUtility/RetiredHacker.md
          - Insane Drug Dealer: rolelist/interlooper/InterlooperUtility/InsaneDrugDealer.md
          - Disconnected Paragon Operative: rolelist/interlooper/InterlooperUtility/DisconnectedParagonOperative.md
        - Interlooper Chaos:
          - Corrupt Detective: rolelist/interlooper/InterlooperChaos/CorruptDetective.md
          - Corrupt Lawyer: rolelist/interlooper/InterlooperChaos/CorruptLawyer.md
          - Waxmart Manager: rolelist/interlooper/InterlooperChaos/WaxmartManager.md
          - Reminiscing Amnesiac: rolelist/interlooper/InterlooperChaos/ReminiscingAmnesiac.md
          - King of Trolls: rolelist/interlooper/InterlooperChaos/KingOfTrolls.md
          - Wildcard: rolelist/interlooper/InterlooperChaos/Wildcard.md
          - Drunken Agent: rolelist/interlooper/InterlooperChaos/DrunkenAgent.md
        - Interlooper Killing:
          - Rogue Mastermind: rolelist/interlooper/InterlooperKilling/RogueMastermind.md
          - Psychopath: rolelist/interlooper/InterlooperKilling/Psychopath.md
          - Bombardier: rolelist/interlooper/InterlooperKilling/Bombadier.md
          - Rogue Assassin: rolelist/interlooper/InterlooperKilling/RogueAssassin.md
          - F/A-18 Super Hornet Pilot: rolelist/interlooper/InterlooperKilling/FA18SuperHornetPilot.md
          - Underground Ring Fighter: rolelist/interlooper/InterlooperKilling/UndergroundRingFighter.md
          - Italian Mafia: rolelist/interlooper/InterlooperKilling/ItalianMafia.md
      - Fed:
        - Fed: rolelist/fed/fed.md
        - Fed Special:
          - Runaway Snitch: rolelist/fed/FedSpecial/RunawaySnitch.md
        - Fed Field Operations:
          - Field Agent: rolelist/fed/FedFieldOps/FieldFed.md
          - Determined Deputy: rolelist/fed/FedFieldOps/DeterminedDeputy.md
          - Police Chief: rolelist/fed/FedFieldOps/PoliceChief.md
          - K-9 Unit: rolelist/fed/FedFieldOps/K9Unit.md
          - Police Car Driver: rolelist/fed/FedFieldOps/PoliceCarDriver.md
          - Independent Contractor: rolelist/fed/FedFieldOps/IndependentContractor.md
        - Fed Investigative:
          - Forensic Specialist: rolelist/fed/FedInvest/ForensicSpecialist.md
          - Rookie Informant: rolelist/fed/FedInvest/RookieInformant.md
          - Cybercrime Investigator: rolelist/fed/FedInvest/CybercrimeInvestigator.md
          - Helicopter Operator: rolelist/fed/FedInvest/HelicopterOperator.md
          - Narcotics Officer: rolelist/fed/FedInvest/NarcoticsOfficer.md
        - Fed Offensive:
          - Agent Leader: rolelist/fed/FedOffensive/AgentLeader.md
          - Cipher Lord: rolelist/fed/FedOffensive/CipherLord.md
          - Expert Whitehat: rolelist/fed/FedOffensive/ExpertWhitehat.md
          - Drone Operator: rolelist/fed/FedOffensive/DroneOperator.md
          - Robocop: rolelist/fed/FedOffensive/Robocop.md
        - Fed Utility:
          - Commissary Officer: rolelist/fed/FedUtility/CommissaryOfficer.md
          - Criminal Psychologist: rolelist/fed/FedUtility/CriminalPsychologist.md
          - Master Manipulator: rolelist/fed/FedUtility/MasterManipulator.md
          - Jail Warden: rolelist/fed/FedUtility/JailWarden.md
          - Animal Tamer: rolelist/fed/FedUtility/AnimalTamer.md
        - Fed Chaos:
          - District Attorney: rolelist/fed/FedChaos/DistrictAttorney.md
          - Vigilante Decipherer: rolelist/fed/FedChaos/VigilanteDecipherer.md
          - Elusive Framer: rolelist/fed/FedChaos/ElusiveFramer.md
          - Persuaded News Reporter: rolelist/fed/FedChaos/PersuadedNewsReporter.md
        - Mole Fed Field Operations:
          - Fed Enforcer: rolelist/fed/MoleFedFieldOps/FedEnforcer.md
          - Fed CCTV Specialist: rolelist/fed/MoleFedFieldOps/FedCCTVSpecialist.md
          - Fed Hardware Hacker: rolelist/fed/MoleFedFieldOps/FedHardwareHacker.md
          - Specialist: rolelist/fed/MoleFedFieldOps/Specialist.md
        - Mole Fed Investigative:
          - Fed Data Scientist: rolelist/fed/MoleFedInvest/FedDataScientist.md
          - Fed Social Engineer: rolelist/fed/MoleFedInvest/FedSocialEngineer.md
          - Fed Ethical Hacker: rolelist/fed/MoleFedInvest/FedEthicalHacker.md
          - Initiator: rolelist/fed/MoleFedInvest/Initiator.md
        - Mole Fed Offensive:
          - Fed Whitehat: rolelist/fed/MoleFedOffensive/FedWhitehat.md
          - Fed Network Specialist: rolelist/fed/MoleFedOffensive/FedNetworkSpecialist.md
          - Fed Network Architect: rolelist/fed/MoleFedOffensive/FedNetworkArchitect.md
          - Fed Graph Theorist: rolelist/fed/MoleFedOffensive/FedGraphTheorist.md
          - Operator: rolelist/fed/MoleFedOffensive/Operator.md
        - Mole Fed Utility:
          - Fed Company Man: rolelist/fed/MoleFedUtility/FedCompanyMan.md
          - Fed Database Manager: rolelist/fed/MoleFedUtility/FedDatabaseManager.md
          - Fed Propagandist: rolelist/fed/MoleFedUtility/FedPropagandist.md
        - Mole Fed Chaos:
          - Fed Amateur Investigator: rolelist/fed/MoleFedChaos/FedAmateurInvestigator.md
          - Fed Technical Recruiter: rolelist/fed/MoleFedChaos/FedTechnicalRecruiter.md
          - Fed Repressed Refugee: rolelist/fed/MoleFedChaos/FedRepressedRefugee.md
      # - W3C:
      #   - W3C: rolelist/w3c/w3c.md
      #   - W3C Special:
      #   - W3C Field Operations:
      #     - W3C Enforcer: rolelist/w3c/W3CFieldOps/W3CEnforcer.md
      #     - W3C Blackmailer: rolelist/w3c/W3CFieldOps/W3CBlackmailer.md
      #   - W3C Investigative:
      #     - W3C Stalker: rolelist/w3c/W3CInvest/W3CStalker.md
      #     - W3C Forger: rolelist/w3c/W3CInvest/W3CForger.md
      #     - W3C Ambusher: rolelist/w3c/W3CInvest/W3CAmbusher.md
      #   - W3C Offensive:
      #     - W3C Blackhat: rolelist/w3c/W3COffensive/W3CBlackhat.md
      #     - W3C Disruptor: rolelist/w3c/W3COffensive/W3CDisruptor.md
      #     - W3C Graph Theorist: rolelist/w3c/W3COffensive/W3CGraphTheorist.md
      #   - W3C Utility:
      #     - W3C Lab Technician: rolelist/w3c/W3CUtility/W3CLabTechnician.md
      #     - W3C Insider: rolelist/w3c/W3CUtility/W3CInsider.md
      #     - W3C Janitor: rolelist/w3c/W3CUtility/W3CJanitor.md
      #   - W3C Chaos:
      #     - W3C Technical Recruiter: rolelist/w3c/W3CChaos/W3CTechnicalRecruiter.md
      #     - W3C Assassin: rolelist/w3c/W3CChaos/W3CAssassin.md
      # - Paragon:
      #   - Paragon: rolelist/paragon/paragon.md
      #   - Paragon Special:
      #   - Paragon Field Operations:
      #     - Paragon Ex-Mercenary: rolelist/paragon/ParagonFieldOps/ParagonExMercenary.md
      #     - Paragon Influencer: rolelist/paragon/ParagonFieldOps/ParagonInfluencer.md
      #   - Paragon Investigative:
      #     - Paragon Journalist: rolelist/paragon/ParagonInvest/ParagonJournalist.md
      #     - Paragon Informant: rolelist/paragon/ParagonInvest/ParagonInformant.md
      #     - Paragon Search Engine Optimizer: rolelist/paragon/ParagonInvest/ParagonSearchEngineOptimizer.md
      #   - Paragon Offensive:
      #     - Paragon Prodigy: rolelist/paragon/ParagonOffensive/ParagonProdigy.md
      #     - Paragon Cryptographer: rolelist/paragon/ParagonOffensive/ParagonCryptographer.md
      #   - Paragon Utility:
      #     - Paragon Security Specialist: rolelist/paragon/ParagonUtility/ParagonSecuritySpecialist.md
      #     - Paragon Scout: rolelist/paragon/ParagonUtility/ParagonScout.md
      #   - Paragon Chaos:
      #     - Paragon Head of Personnel: rolelist/paragon/ParagonChaos/ParagonHeadOfPersonnel.md
      #     - Paragon Ex-Mole: rolelist/paragon/ParagonChaos/ParagonExMole.md
      #     - Paragon Assassin: rolelist/paragon/ParagonChaos/ParagonAssassin.md